table! {
    /// Representation of the `tag_rule_groups` table.
    ///
    /// (Automatically generated by Diesel.)
    tag_rule_groups (global_id) {
        /// The `global_id` column of the `tag_rule_groups` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        global_id -> Text,
        /// The `data` column of the `tag_rule_groups` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        data -> Text,
    }
}
