table! {
    /// Representation of the `extracted_current` table.
    ///
    /// (Automatically generated by Diesel.)
    extracted_current (utc_date) {
        /// The `utc_date` column of the `extracted_current` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        utc_date -> Text,
        /// The `extracted_timestamp` column of the `extracted_current` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        extracted_timestamp -> Text,
        /// The `raw_events_changed_timestamp` column of the `extracted_current` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        raw_events_changed_timestamp -> Text,
    }
}

table! {
    /// Representation of the `extracted_events` table.
    ///
    /// (Automatically generated by Diesel.)
    extracted_events (rowid) {
        /// The `rowid` column of the `extracted_events` table.
        ///
        /// Its SQL type is `BigInt`.
        ///
        /// (Automatically generated by Diesel.)
        rowid -> BigInt,
        /// The `timestamp` column of the `extracted_events` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        timestamp -> Text,
        /// The `duration` column of the `extracted_events` table.
        ///
        /// Its SQL type is `Double`.
        ///
        /// (Automatically generated by Diesel.)
        duration -> Double,
        /// The `event_id` column of the `extracted_events` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        event_id -> Text,
        /// The `tag` column of the `extracted_events` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        tag -> Text,
        /// The `value` column of the `extracted_events` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        value -> Text,
    }
}

table! {
    /// Representation of the `fetcher_cache` table.
    ///
    /// (Automatically generated by Diesel.)
    fetcher_cache (key) {
        /// The `key` column of the `fetcher_cache` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        key -> Text,
        /// The `timestamp` column of the `fetcher_cache` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        timestamp -> Text,
        /// The `value` column of the `fetcher_cache` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        value -> Text,
    }
}

allow_tables_to_appear_in_same_query!(
    extracted_current,
    extracted_events,
    fetcher_cache,
);
