table! {
    /// Representation of the `event_ids` table.
    ///
    /// (Automatically generated by Diesel.)
    event_ids (id) {
        /// The `id` column of the `event_ids` table.
        ///
        /// Its SQL type is `BigInt`.
        ///
        /// (Automatically generated by Diesel.)
        id -> BigInt,
        /// The `raw_id` column of the `event_ids` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        raw_id -> Text,
        /// The `timestamp` column of the `event_ids` table.
        ///
        /// Its SQL type is `BigInt`.
        ///
        /// (Automatically generated by Diesel.)
        timestamp -> BigInt,
        /// The `duration` column of the `event_ids` table.
        ///
        /// Its SQL type is `Double`.
        ///
        /// (Automatically generated by Diesel.)
        duration -> Double,
    }
}

table! {
    /// Representation of the `extracted_current` table.
    ///
    /// (Automatically generated by Diesel.)
    extracted_current (utc_date) {
        /// The `utc_date` column of the `extracted_current` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        utc_date -> Text,
        /// The `extracted_timestamp` column of the `extracted_current` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        extracted_timestamp -> Text,
        /// The `raw_events_changed_timestamp` column of the `extracted_current` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        raw_events_changed_timestamp -> Text,
    }
}

table! {
    /// Representation of the `extracted_events` table.
    ///
    /// (Automatically generated by Diesel.)
    extracted_events (rowid) {
        /// The `rowid` column of the `extracted_events` table.
        ///
        /// Its SQL type is `BigInt`.
        ///
        /// (Automatically generated by Diesel.)
        rowid -> BigInt,
        /// The `event_id` column of the `extracted_events` table.
        ///
        /// Its SQL type is `BigInt`.
        ///
        /// (Automatically generated by Diesel.)
        event_id -> BigInt,
        /// The `timestamp` column of the `extracted_events` table.
        ///
        /// Its SQL type is `BigInt`.
        ///
        /// (Automatically generated by Diesel.)
        timestamp -> BigInt,
        /// The `duration` column of the `extracted_events` table.
        ///
        /// Its SQL type is `Double`.
        ///
        /// (Automatically generated by Diesel.)
        duration -> Double,
        /// The `tag` column of the `extracted_events` table.
        ///
        /// Its SQL type is `BigInt`.
        ///
        /// (Automatically generated by Diesel.)
        tag -> BigInt,
        /// The `value` column of the `extracted_events` table.
        ///
        /// Its SQL type is `BigInt`.
        ///
        /// (Automatically generated by Diesel.)
        value -> BigInt,
    }
}

table! {
    /// Representation of the `fetcher_cache` table.
    ///
    /// (Automatically generated by Diesel.)
    fetcher_cache (key) {
        /// The `key` column of the `fetcher_cache` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        key -> Text,
        /// The `timestamp` column of the `fetcher_cache` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        timestamp -> Text,
        /// The `value` column of the `fetcher_cache` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        value -> Text,
    }
}

table! {
    /// Representation of the `tag_values` table.
    ///
    /// (Automatically generated by Diesel.)
    tag_values (id) {
        /// The `id` column of the `tag_values` table.
        ///
        /// Its SQL type is `BigInt`.
        ///
        /// (Automatically generated by Diesel.)
        id -> BigInt,
        /// The `text` column of the `tag_values` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        text -> Text,
    }
}

table! {
    /// Representation of the `tags` table.
    ///
    /// (Automatically generated by Diesel.)
    tags (id) {
        /// The `id` column of the `tags` table.
        ///
        /// Its SQL type is `BigInt`.
        ///
        /// (Automatically generated by Diesel.)
        id -> BigInt,
        /// The `text` column of the `tags` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        text -> Text,
    }
}

joinable!(extracted_events -> event_ids (event_id));
joinable!(extracted_events -> tag_values (value));
joinable!(extracted_events -> tags (tag));

allow_tables_to_appear_in_same_query!(
    event_ids,
    extracted_current,
    extracted_events,
    fetcher_cache,
    tag_values,
    tags,
);
