table! {
    /// Representation of the `events` table.
    ///
    /// (Automatically generated by Diesel.)
    events (insertion_sequence) {
        /// The `insertion_sequence` column of the `events` table.
        ///
        /// Its SQL type is `BigInt`.
        ///
        /// (Automatically generated by Diesel.)
        insertion_sequence -> BigInt,
        /// The `id` column of the `events` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        id -> Text,
        /// The `timestamp_unix_ms` column of the `events` table.
        ///
        /// Its SQL type is `BigInt`.
        ///
        /// (Automatically generated by Diesel.)
        timestamp_unix_ms -> BigInt,
        /// The `data_type` column of the `events` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        data_type -> Text,
        /// The `duration_ms` column of the `events` table.
        ///
        /// Its SQL type is `BigInt`.
        ///
        /// (Automatically generated by Diesel.)
        duration_ms -> BigInt,
        /// The `data` column of the `events` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        data -> Text,
    }
}

table! {
    /// Representation of the `events_backup_before_2021_01` table.
    ///
    /// (Automatically generated by Diesel.)
    events_backup_before_2021_01 (insertion_sequence) {
        /// The `insertion_sequence` column of the `events_backup_before_2021_01` table.
        ///
        /// Its SQL type is `Nullable<BigInt>`.
        ///
        /// (Automatically generated by Diesel.)
        insertion_sequence -> Nullable<BigInt>,
        /// The `id` column of the `events_backup_before_2021_01` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        id -> Text,
        /// The `timestamp` column of the `events_backup_before_2021_01` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        timestamp -> Text,
        /// The `data_type` column of the `events_backup_before_2021_01` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        data_type -> Text,
        /// The `sampler` column of the `events_backup_before_2021_01` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        sampler -> Text,
        /// The `sampler_sequence_id` column of the `events_backup_before_2021_01` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        sampler_sequence_id -> Text,
        /// The `data` column of the `events_backup_before_2021_01` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        data -> Text,
    }
}

allow_tables_to_appear_in_same_query!(
    events,
    events_backup_before_2021_01,
);
